all: minimax negamax negaScout

minimax:
	g++ -o alpha-beta alpha-beta.cc
	g++ -o minimax minimax.cc

negamax:
	g++ -o negaTest negaTest.cc

negaScout:
	g++ -o negaScout negaScout.cc
	g++ -o scout scout.cc
clean:
	rm alpha-beta minimax negaScout scout negaTest
