main:
	g++ -o alpha-beta alpha-beta.cc
	g++ -o minimax minimax.cc
	g++ -o negaTest negaTest.cc
	g++ -o negaScout negaScout.cc
	g++ -o scout scout.cc
clean:
	rm alpha-beta minimax negaScout scout negaTest
